"""Stable string-valued contracts used by the public CutoffGuard API."""

from enum import Enum


class AuditStatus(str, Enum):
    PASS = "pass"
    REVIEW = "review"
    FAIL = "fail"


class Severity(str, Enum):
    WARNING = "warning"
    ERROR = "error"


class FindingCategory(str, Enum):
    AVAILABILITY = "availability"
    LABEL_MATURITY = "label_maturity"
    REVISION = "revision"
    IDENTITY = "identity"
    SPLIT = "split"
    ARTIFACT = "artifact"
    INPUT = "input"


class FindingCode(str, Enum):
    EMPTY_INPUT = "EMPTY_INPUT"
    DUPLICATE_ID = "DUPLICATE_ID"
    FUTURE_OBSERVATION = "FUTURE_OBSERVATION"
    MISSING_AVAILABILITY = "MISSING_AVAILABILITY"
    POST_CUTOFF_AVAILABILITY = "POST_CUTOFF_AVAILABILITY"
    IMMATURE_LABEL = "IMMATURE_LABEL"
    POST_CUTOFF_REVISION = "POST_CUTOFF_REVISION"
    TRAIN_RECORD_AFTER_CUTOFF = "TRAIN_RECORD_AFTER_CUTOFF"
    TRAIN_INFORMATION_NOT_AVAILABLE = "TRAIN_INFORMATION_NOT_AVAILABLE"
    TRAIN_LABEL_NOT_MATURE = "TRAIN_LABEL_NOT_MATURE"
    SPLIT_ID_OVERLAP = "SPLIT_ID_OVERLAP"
    UNKNOWN_RECORD_ID = "UNKNOWN_RECORD_ID"
    ARTIFACT_BUILT_AFTER_CUTOFF = "ARTIFACT_BUILT_AFTER_CUTOFF"
    ARTIFACT_FIT_AFTER_CUTOFF = "ARTIFACT_FIT_AFTER_CUTOFF"
    ARTIFACT_USES_EVAL_SPLIT = "ARTIFACT_USES_EVAL_SPLIT"
    INVALID_CUTOFF_ORDER = "INVALID_CUTOFF_ORDER"
    MISSING_SPLIT = "MISSING_SPLIT"
    EMPTY_TRAIN_SPLIT = "EMPTY_TRAIN_SPLIT"
    MANIFEST_PATH_ESCAPE = "MANIFEST_PATH_ESCAPE"
    EVALUATION_RECORD_AFTER_CUTOFF = "EVALUATION_RECORD_AFTER_CUTOFF"
    EVALUATION_INFORMATION_NOT_AVAILABLE = "EVALUATION_INFORMATION_NOT_AVAILABLE"
    EVALUATION_LABEL_NOT_MATURE = "EVALUATION_LABEL_NOT_MATURE"
    DUPLICATE_ARTIFACT_ID = "DUPLICATE_ARTIFACT_ID"
    UNKNOWN_SOURCE_SPLIT = "UNKNOWN_SOURCE_SPLIT"
